# Generated by Django 5.2.5 on 2025-08-11 07:35

import django.core.serializers.json
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('contest_theme', models.CharField(max_length=255)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('form_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'verbose_name': 'Team Registration',
                'verbose_name_plural': 'Team Registrations',
                'ordering': ['-submission_date'],
            },
        ),
    ]
